# ABOUT

[[main]]
  name = "About"
  weight = 10
  url = "/about/"

[[main]]
  name = "Abstract"
  weight = 1
  url = "/about/abstract/"
  parent = "About"

[[main]]
  name = "Core"
  weight = 2
  url = "/about/core/"
  parent = "About"

[[main]]
  name = "Kernels"
  weight = 3
  url = "/about/kernels/"
  parent = "About"

[[main]]
  name = "Tools"
  weight = 4
  url = "/about/tools/"
  parent = "About"

[[main]]
  name = "Tutorials"
  weight = 5
  url = "https://github.com/kokkos/kokkos-tutorials"
  parent = "About"

[[main]]
  name = "News"
  weight = 6
  url = "/blog/"
  parent = "About"

# REPOSITORIES

[[main]]
  name = "Repositories"
  weight = 20
  url = "/repositories/"

[[main]]
  name = "Core"
  weight = 1
  url = "https://github.com/kokkos/kokkos"
  parent = "Repositories"

[[main]]
  name = "Kernels"
  weight = 2
  url = "https://github.com/kokkos/kokkos-kernels"
  parent = "Repositories"

[[main]]
  name = "Tools"
  weight = 3
  url = "https://github.com/kokkos/kokkos-tools"
  parent = "Repositories"

[[main]]
  name = "Tutorials"
  weight = 4
  url = "https://github.com/kokkos/kokkos-tutorials"
  parent = "Repositories"

# DOCUMENTATION

[[main]]
  name = "Documentation"
  weight = 30
  url = "/documentation/"

# BLOG

[[main]]
  name = "Blog"
  weight = 40
  url = "/blog/"

# OUTREACH

[[main]]
  name = "Outreach"
  weight = 50
  url = "/outreach/"

[[main]]
  name = "Events"
  weight = 1
  url = "/outreach/events"
  parent = "Outreach"

[[main]]
  name = "Publications"
  weight = 2
  url = "/outreach/publications"
  parent = "Outreach"

[[main]]
  name = "Report An Issue"
  weight = 3
  url = "/outreach/report-an-issue"
  parent = "Outreach"

[[main]]
  name = "Slack Channel"
  weight = 4
  url = "https://app.slack.com/client/T5ASL2F1N"
  parent = "Outreach"

# COMMUNITY

[[main]]
  name = "Community"
  weight = 60
  url = "/community/"

[[main]]
  name = "Team"
  weight = 1
  url = "/community/team/"
  parent = "Community"

[[main]]
  name = "Use Case Studies"
  weight = 2
  url = "/community/use-case-studies/"
  parent = "Community"

[[main]]
  name = "Applications"
  weight = 3
  url = "/community/applications/"
  parent = "Community"     

# CONTACT

[[main]]
  name = "Contact"
  weight = 70
  url = "/contact/"